[rules]
license-not-found = {level = "off", source-shasum = "108f250ff79cc103b464b3ef41fa60f4866e4e6c962117171adaac7325ebdab2"}
missing-license = {level = "off", source-shasum = "108f250ff79cc103b464b3ef41fa60f4866e4e6c962117171adaac7325ebdab2"}
unused-runpath-entry = {level = "off"}
env-script-interpreter-not-found = {level = "off"}
