[rules]
license-not-found = {level = "off", source-shasum = "77972184077d8715cc22b7ed1f7c246fc6b1e0bae0667a366db8ccdc3000cf73"}
missing-license = {level = "off", source-shasum = "77972184077d8715cc22b7ed1f7c246fc6b1e0bae0667a366db8ccdc3000cf73"}
unused-runpath-entry = {level = "off"}
