[rules]
license-not-found = {level = "off", source-shasum = "f66390a661faa117d00fab2e79cf2dc9d097b42cc296bf3f8677d1e7b452dc3a"}
missing-license = {level = "off", source-shasum = "f66390a661faa117d00fab2e79cf2dc9d097b42cc296bf3f8677d1e7b452dc3a"}
unused-dependency = {ignored_packages = [
    "core/bash-static",
    "core/hab-ld-wrapper",
    "core/gcc-libs"
]}
unused-runpath-entry = {level = "off"}
