[rules]
missing-license = { level = "off", source-shasum="c9cc77c7c560c543135edc555af609d5619dbef011997e988ce40a3d75d86088" }
license-not-found = { level = "off", source-shasum="c9cc77c7c560c543135edc555af609d5619dbef011997e988ce40a3d75d86088" }
unused-runpath-entry = {level = "off"}
