[rules]
license-not-found = {level = "off", source-shasum = "537512904744b35e232912055ccf8ec66d768639ff3abe5788d90d792ec5f48b"}
missing-license = {level = "off", source-shasum = "537512904744b35e232912055ccf8ec66d768639ff3abe5788d90d792ec5f48b"}
unused-runpath-entry = {level = "off"}
