[rules]
license-not-found = {level = "off", source-shasum = "695e9827fdf763513f133910bc7e6cfdb9187943a4fec943e57449723d2b8dbf"}
missing-license = {level = "off", source-shasum = "695e9827fdf763513f133910bc7e6cfdb9187943a4fec943e57449723d2b8dbf"}
unused-runpath-entry = {level = "off"}
