[rules]
license-not-found = {level = "off", source-shasum = "27e55cf7083913bfb6826ca78cde9de7647cded648d35f24163f2d31bb9f51cd"}
missing-license = {level = "off", source-shasum = "27e55cf7083913bfb6826ca78cde9de7647cded648d35f24163f2d31bb9f51cd"}
unused-runpath-entry = {level = "off"}
