[rules]
# Glibc unfortunately uses bashisms in the ldd, tzselect scripts so it's interpreter
# needs to be /bin/bash, but we haven't built bash yet. Since this package is
# only intended to be used within a studio where /bin/bash will be binlinked we let this pass
host-script-interpreter = {ignored_files = ["bin/tzselect", "bin/ldd"]}
license-not-found = {level = "off", source-shasum = "a5a26b22f545d6b7d7b3dd828e11e428f24f4fac43c934fb071b6a7d0828e901"}
missing-license = {level = "off", source-shasum = "a5a26b22f545d6b7d7b3dd828e11e428f24f4fac43c934fb071b6a7d0828e901"}
# Certain glibc headers include the linux headers, making it a runtime dependency
unused-dependency = {ignored_packages = ["core/linux-headers"]}
