[rules]
missing-license = {level = "off", source-shasum = "be4ba7b777100c851ab268e95f70f405d28d7813ba60a9bdcf4e88c88acf8602"}
# Some rust files in the docs start with #![feature(...)] which is misinterpreted as a script
script-interpreter-not-found = {ignored_files = ["*.rs"]}
library-dependency-not-found = {ignored_files = ["lib/*"]}
unused-runpath-entry = {ignored_files = ["lib/*"]}
unused-rpath-entry = {ignored_files = ["lib/*"]}
host-elf-interpreter = {level = "off"}
# The following dependencies are needed at runtime by Cargo for the associated reasons:
# 1. core/cacerts - Provides SSL certificates necessary for secure connections.
# 2. core/binutils - Supplies the 'ld' linker, utilized indirectly by Rust through gcc.
# 3. core/tzdata - Needed for the proper operation of the GNU C Library (glibc).
# 4. core/iana-etc - Also required for the functioning of glibc.
unused-dependency = {ignored_packages = [
    "core/{cacerts,binutils,tzdata,iana-etc}"
]}
