[rules]
license-not-found = {level = "off", source-shasum = "766e48423e79359ea31e41db9e5c289675947a7fcf2efdcedb726ac9d0da3784"}
missing-license = {level = "off", source-shasum = "766e48423e79359ea31e41db9e5c289675947a7fcf2efdcedb726ac9d0da3784"}
