[rules]
missing-license = {level = "off", source-shasum = "b23ad7fd9f73e43ad1767e636040e88ba7c9e5775bfa5618436a0dd2c17c3716"}
unused-dependency = {level = "off"}
unused-runpath-entry = {level = "off"}
library-dependency-not-found = { level = "off" }
empty-top-level-directory = {level = "off"}
