[rules]
missing-license = {level = "off", source-shasum = "344d0a79f1a9b08029b0744e2cc401a43f9c90acd1044d09a530b4885a8e9fc0"}
unused-dependency = {level = "off"}
unused-runpath-entry = {level = "off"}
library-dependency-not-found = { level = "off" }
empty-top-level-directory = {level = "off"}
