[rules]
license-not-found = {level = "off", source-shasum = "554801054694ff7d8a7abdf0d6ece34e2f16e111673cc01b8c9ee1278451181e"}
missing-license = {level = "off", source-shasum = "554801054694ff7d8a7abdf0d6ece34e2f16e111673cc01b8c9ee1278451181e"}
unused-runpath-entry = {level = "off"}
