[rules]
missing-license = { level = "off", source-shasum = "02f8c45bb379ed0c3de7514fad48c714fd46be8f0b536bfd5320050165a1ee26" }
license-not-found = { level = "off", source-shasum = "02f8c45bb379ed0c3de7514fad48c714fd46be8f0b536bfd5320050165a1ee26" }
# Perl handles the shebangs itself in certain scripts. So `#!perl` and `#!./perl` are considered valid.
# https://stackoverflow.com/questions/45949339/how-does-perl-handle-the-shebang-line
script-interpreter-not-found = {ignored_files = ["lib/perl5/5.*.*/*"]}
# These are required at runtime by certain scripts
unused-dependency = {ignored_packages = ["core/{coreutils,less}"]}
unused-runpath-entry = {level = "off"}
