[rules]
# Ignore sample scripts
host-script-interpreter = {ignored_files = ["share/**/*.sample"]}
license-not-found = {level = "off", source-shasum = "f8047f572f665bebeb637fd5f14678f31b3ca5d2ff9a18f20bd925bd48f75d3c"}
missing-license = {level = "off", source-shasum = "f8047f572f665bebeb637fd5f14678f31b3ca5d2ff9a18f20bd925bd48f75d3c"}
# These packages are needed are runtime
unused-dependency = {ignored_packages = ["core/{gettext,sed,cacerts,openssh,gcc-libs}"]}
unused-runpath-entry = {level = "off"}
missing-script-interpreter-dependency = {level = "off"}
