[rules]
# ignore examples with host script interpreters
host-script-interpreter = {ignored_files = ["*-example.{bash,tcsh}"]}
license-not-found = {level = "off", source-shasum = "5c1daf733b04e9859afdc3bd87cc481180ee0f88b5c0946b16fdec931975fb79"}
missing-license = {level = "off", source-shasum = "5c1daf733b04e9859afdc3bd87cc481180ee0f88b5c0946b16fdec931975fb79"}
unused-runpath-entry = {level = "off"}
