[rules]
missing-license = { level = "off", source-shasum = "0e5be4d2937e8bd9b7cd60d46721ce79f88a33415dd68c2d738fb5924638f656" }
license-not-found = { level = "off", source-shasum = "0e5be4d2937e8bd9b7cd60d46721ce79f88a33415dd68c2d738fb5924638f656" }
# These are rpath entries added by the build system
unused-runpath-entry = {ignored_files = ["lib/lib{history,readline}.so*"]}
