[rules]
license-not-found = {level = "off", source-shasum = "3311dff32e746499f4df0d5df04d7eb396382d7e108bb9250e7b519b837043a4"}
missing-license = {level = "off", source-shasum = "3311dff32e746499f4df0d5df04d7eb396382d7e108bb9250e7b519b837043a4"}