[rules]
license-not-found = {level = "off", source-shasum = "9599b22ecd1d5787ad7d3b7bf0c59f312b3396d1e281175dd1f8a4014da621ff"}
missing-license = {level = "off", source-shasum = "9599b22ecd1d5787ad7d3b7bf0c59f312b3396d1e281175dd1f8a4014da621ff"}
unused-runpath-entry = {level = "off"}
