[rules]
license-not-found = {level = "off", source-shasum = "09418a6d8fb83f5113f5bd856e09703df5d37bae0308c668d0f346e3d3f0a56f"}
missing-license = {level = "off", source-shasum = "09418a6d8fb83f5113f5bd856e09703df5d37bae0308c668d0f346e3d3f0a56f"}
