[rules]
license-not-found = {level = "off", source-shasum = "2819f55564d86d542abbecafd82ff61e819a3eec967faa36cd3e68f1596a44b8"}
missing-license = {level = "off", source-shasum = "2819f55564d86d542abbecafd82ff61e819a3eec967faa36cd3e68f1596a44b8"}
unused-runpath-entry = {level = "off"}
