[rules]
# Parallel has multiple environment files for different shells
env-script-interpreter-not-found = {ignored_files = [
    "bin/env_parallel*",
    "bin/parset"
]}
license-not-found = {level = "off", source-shasum = "b4b28f475f8cff8bb6ed4b03cc5a67041f18fc73fa256923b23181b56afdb2cb"}
missing-license = {level = "off", source-shasum = "b4b28f475f8cff8bb6ed4b03cc5a67041f18fc73fa256923b23181b56afdb2cb"}
# The binaries in procps-ng are used at runtime by parallel
unused-dependency = {ignored_packages = ["core/procps-ng"]}
