[rules]
license-not-found = {level = "off", source-shasum = "1bd6aa42275313af3141c7cf2e5b964e8b1fd488025caf2f971f43b00776b332"}
missing-license = {level = "off", source-shasum = "1bd6aa42275313af3141c7cf2e5b964e8b1fd488025caf2f971f43b00776b332"}
unused-runpath-entry = {level = "off"}
