[rules]
# Ignore example script interpreters
host-script-interpreter = {ignored_files = ["share/doc/gettext/examples/*"]}
license-not-found = {level = "off", source-shasum = "c918503d593d70daf4844d175a13d816afacb667c06fba1ec9dcd5002c1518b7"}
missing-license = {level = "off", source-shasum = "c918503d593d70daf4844d175a13d816afacb667c06fba1ec9dcd5002c1518b7"}
# These are both false positives because the gcc-libs runpath is
# added to several libraries and binaries
missing-runpath-entry-dependency = {level = "off"}
script-interpreter-not-found = {ignored_files = [
    "share/doc/gettext/examples/*"
]}
# These packages are all used within scripts in gettext
unused-dependency = {ignored_packages = [
    "core/sed",
    "core/coreutils",
    "core/gzip",
    "core/sed",
    "core/xz",
    "core/bzip2"
]}
unused-runpath-entry = {level = "off"}
