[rules]
missing-license = {level = "off", source-shasum = "91cb8fa61771c63c262efb553059b7c7ad6757afa5857af6265e4b0bdc2a14a5"}
# The build system adds a rpath for the $pkg_prefix/lib folder,
# unused-runpath-entry = { ignored_files = ["lib/libtcl*.so"] }
# TZ data is used at runtime
unused-dependency = {ignored_packages = ["core/tzdata"]}
unused-runpath-entry = {level = "off"}
