[rules]
unused-runpath-entry = {ignored_files = ["libexec/coreutils/libstdbuf.*"]}
license-not-found = {level = "off", source-shasum = "7a0124327b398fd9eb1a6abde583389821422c744ffa10734b24f557610d3283"}
missing-license = {level = "off", source-shasum = "7a0124327b398fd9eb1a6abde583389821422c744ffa10734b24f557610d3283"}