[rules]
unused-runpath-entry = {ignored_files = ["libexec/coreutils/libstdbuf.*"]}
license-not-found = {level = "off", source-shasum = "e8bb26ad0293f9b5a1fc43fb42ba970e312c66ce92c1b0b16713d7500db251bf"}
missing-license = {level = "off", source-shasum = "e8bb26ad0293f9b5a1fc43fb42ba970e312c66ce92c1b0b16713d7500db251bf"}