[rules]
missing-license = { level = "off", source-shasum = "01a7b881bd220bfdf615f97b8718f80bdfd3f6add385b993dcf6efd14e8c0ac6" }
license-not-found = { level = "off", source-shasum = "01a7b881bd220bfdf615f97b8718f80bdfd3f6add385b993dcf6efd14e8c0ac6" }
# grep, diffutils and coreutils are used in certain scripts of the gzip package
unused-dependency = {ignored_packages = [
    "core/coreutils",
    "core/diffutils",
    "core/grep",
    "core/less"
]}
