[rules]
license-not-found = {level = "off", source-shasum = "bde832a5e3344dc723cfe9cc37f8e54bde04565bfe6f136bc1bd31ab352e9fab"}
missing-license = {level = "off", source-shasum = "bde832a5e3344dc723cfe9cc37f8e54bde04565bfe6f136bc1bd31ab352e9fab"}
unused-runpath-entry = {level = "off"}
