[rules]
license-not-found = {level = "off", source-shasum = "e0dc77297625631ac8e50fa92fffefe899a4eb702592da5c32ef04e2293aca3a"}
missing-license = {level = "off", source-shasum = "e0dc77297625631ac8e50fa92fffefe899a4eb702592da5c32ef04e2293aca3a"}
# hab-cc-wrapper is used at runtime
unused-dependency = {ignored_packages = [
    "core/hab-cc-wrapper"
]}
unused-runpath-entry = {level = "off"}
