[rules]
license-not-found = {level = "off", source-shasum = "a7b39bc69cbf9e25826c5a60ab26477001f7c08d85cec04bc0e29cabed6f3cc9"}
missing-license = {level = "off", source-shasum = "a7b39bc69cbf9e25826c5a60ab26477001f7c08d85cec04bc0e29cabed6f3cc9"}
# hab-cc-wrapper is used at runtime
unused-dependency = {ignored_packages = [
    "core/hab-cc-wrapper"
]}
unused-runpath-entry = {level = "off"}
