[rules]
missing-license = { level = "off", source-shasum = "1db2aedde89d0dea42b16d9528f894c8d15dae4e190b59aecc78f5a951276eab" }
license-not-found = { level = "off", source-shasum = "1db2aedde89d0dea42b16d9528f894c8d15dae4e190b59aecc78f5a951276eab" }
unused-runpath-entry = { level = "off" }
unused-dependency = { level = "off" }
