[rules]
# Ignore test scripts that intentionally use python instead of python3.
# This is because python must always invoke python2 on debian based systems
env-script-interpreter-not-found = {ignored_files = ["lib/*"]}
# These scripts are only used for tests and can be ignored
host-script-interpreter = {ignored_files = ["lib/python*/test/*"]}
missing-license = {level = "off", source-shasum = "2666038f1521b7a8ec34bf2997b363778118d6f3979282c93723e872bcd464e0"}
unused-runpath-entry = {level = "off"}
missing-runpath-entry-dependency = {level = "off"}
library-dependency-not-found = {level = "off"}
