[rules]
host-script-interpreter = {level = "off"}
license-not-found = {level = "off", source-shasum = "da8ebb2ce4dcf46b90098daf962cffa68f4b4f62ea60f798d0ef12929ede6adf"}
missing-license = {level = "off", source-shasum = "da8ebb2ce4dcf46b90098daf962cffa68f4b4f62ea60f798d0ef12929ede6adf"}
unused-dependency = {ignored_packages = [ "core/{coreutils,m4,binutils,sed,grep,file}"]}
unused-runpath-entry = {level = "off"}
