[rules]
missing-license = { level = "off", source-shasum = "fa41b3a85413af87fb5e3a7d9c8fa8d4a20728c67651185bb49c38a7f9382b1e" }
license-not-found = { level = "off", source-shasum = "fa41b3a85413af87fb5e3a7d9c8fa8d4a20728c67651185bb49c38a7f9382b1e" }
unused-runpath-entry = {ignored_files = ["lib/gawk/*.so", "libexec/{awk,gawk}/{pwcat,grcat}"]}
