[rules]
license-not-found = {level = "off", source-shasum = "8ca4f2a77ba7aac20aca3e3517a2c96cfcf7c6b064ab7d4a0809e7e4e9eb9914"}
missing-license = {level = "off", source-shasum = "8ca4f2a77ba7aac20aca3e3517a2c96cfcf7c6b064ab7d4a0809e7e4e9eb9914"}
unused-runpath-entry = {level = "off"}
