[rules]
license-not-found = {level = "off", source-shasum = "a73ef05fe37dd585f7d87068e4a0639760419f810138bd75c61ddaa1f9e2131e"}
missing-license = {level = "off", source-shasum = "a73ef05fe37dd585f7d87068e4a0639760419f810138bd75c61ddaa1f9e2131e"}
