[rules]
license-not-found = {level = "off", source-shasum = "a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898"}
missing-license = {level = "off", source-shasum = "a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898"}
# The gcc-base runpath dependency is not required as gcc-libs is present
missing-runpath-entry-dependency = {ignored_files = ["lib/libgmpxx.so*"]}
# These entries are added by the build system
unused-runpath-entry = {ignored_files = ["lib/lib{gmp,gmpxx}.so*"]}
