[rules]
license-not-found = {level = "off", source-shasum = "021a2e709a0edf4250b1256bd5a9e500411a90dddabea830ed59cef90eb9d85c"}
missing-license = {level = "off", source-shasum = "021a2e709a0edf4250b1256bd5a9e500411a90dddabea830ed59cef90eb9d85c"}
unused-runpath-entry = {level = "off"}
