[rules]
license-not-found = {level = "off", source-shasum = "ba885c1319578d6c94d46e9b0dceb4014caafe2490e437a0dbca3f270a223f5a"}
missing-license = {level = "off", source-shasum = "ba885c1319578d6c94d46e9b0dceb4014caafe2490e437a0dbca3f270a223f5a"}
# m4 is used at runtime
unused-dependency = {ignored_packages = ["core/m4"]}
