[rules]
license-not-found = {level = "off", source-shasum = "c2e6d193cc78f84cd6ddb72aaf6d5c6a9162f0470e5992092057f5ff518562fa"}
missing-license = {level = "off", source-shasum = "c2e6d193cc78f84cd6ddb72aaf6d5c6a9162f0470e5992092057f5ff518562fa"}
unused-runpath-entry = {level = "off"}
