[rules]
missing-license = { level = "off", source-shasum = "1387e0b67ff247d2abde998f90dfbf70c1491391a59ddfecb8ae698789f0a4f5" }
license-not-found = { level = "off", source-shasum = "1387e0b67ff247d2abde998f90dfbf70c1491391a59ddfecb8ae698789f0a4f5" }
