[rules]
missing-license = { level = "off", source-shasum = "18543682cffe511407ef6a61af6df842d60232fad58c7c02544ae5860107e6be" }
license-not-found = { level = "off", source-shasum = "18543682cffe511407ef6a61af6df842d60232fad58c7c02544ae5860107e6be" }
# We ignore scripts in the share folder
host-script-interpreter = {ignored_files = ["share/*"]}
missing-script-interpreter-dependency = {level = "off", ignored_files = ["share/*"]}
unused-runpath-entry = {ignored_files = ["bin/*"]}
