[rules]
license-not-found = {level = "off", source-shasum = "0329d7788fbef113fa82cb80889ca197a344ce0df7646fe000974c5d714363a6"}
missing-license = {level = "off", source-shasum = "0329d7788fbef113fa82cb80889ca197a344ce0df7646fe000974c5d714363a6"}
# gawk is used by the texindex binary
unused-dependency = {ignored_packages = ["core/gawk"]}
unused-runpath-entry = {level = "off"}
