[rules]
# ignore interpreters in the cmake modules, not sure if this is ok
env-script-interpreter-not-found = {ignored_files = ["share/cmake-*/Modules/*"]}
host-script-interpreter = {ignored_files = ["share/cmake-3.25/Modules/Compiler/XL-Fortran/cpp"]}
license-not-found = {level = "off", source-shasum = "8d3537b7b7732660ea247398f166be892fe6131d63cc291944b45b91279f3ffb"}
missing-license = {level = "off", source-shasum = "8d3537b7b7732660ea247398f166be892fe6131d63cc291944b45b91279f3ffb"}
script-interpreter-not-found = {ignored_files = ["share/cmake-*/Modules/*"]}
unused-dependency = {ignored_packages = ["core/nghttp2", "core/bzip2", "core/openssl", "core/zstd", "core/xz"]}
unused-runpath-entry = {level = "off"}
