[rules]
license-not-found = {level = "off", source-shasum = "269e3f2e512cbd3314849982014dc199a7b2148cf5c91cedc6db629acdf5e09b"}
missing-license = {level = "off", source-shasum = "269e3f2e512cbd3314849982014dc199a7b2148cf5c91cedc6db629acdf5e09b"}
unused-runpath-entry = {level = "off"}
