[rules]
license-not-found = {level = "off", source-shasum = "5f2bdbad629707aa7d85c623f994aa8a1d2dec55a73de5205bac0bf6058a2f7c"}
missing-license = {level = "off", source-shasum = "5f2bdbad629707aa7d85c623f994aa8a1d2dec55a73de5205bac0bf6058a2f7c"}
unused-runpath-entry = {level = "off"}
