[rules]
license-not-found = {level = "off", source-shasum = "277807353a6726978996945af13e52829e3abd7a9a5b7fb2793894e18f1fcbb2"}
missing-license = {level = "off", source-shasum = "277807353a6726978996945af13e52829e3abd7a9a5b7fb2793894e18f1fcbb2"}
unused-runpath-entry = {level = "off"}
