[rules]
license-not-found = {level = "off", source-shasum = "8920c1fc411e13b90bf704ef9db6f29d540e76d232cb3b2c9f4dc4cc599bd990"}
missing-license = {level = "off", source-shasum = "8920c1fc411e13b90bf704ef9db6f29d540e76d232cb3b2c9f4dc4cc599bd990"}
# autoconf is used by automake at run time
unused-dependency = {ignored_packages = ["core/autoconf"]}
