[rules]
license-not-found = {level = "off", source-shasum = "3b08f5f4f9b4eb82f151a7040bfd6fe6c6fb922efe4b1659c66ea933276965e8"}
missing-license = {level = "off", source-shasum = "3b08f5f4f9b4eb82f151a7040bfd6fe6c6fb922efe4b1659c66ea933276965e8"}
unused-runpath-entry = {level = "off"}
